### PR TITLE
Support security defenition in OpenAPI docs

### PR DESCRIPTION
**Pull request by tyzhnenko**
Add to APIDocsHandler __call__ security parameter

```python
    @docs(
        security=[
            SecurityInfo("basicAuth", []),
            SecurityInfo("bearerAuth", ["read:home", "write:home"]),
        ]
    )
```

Add to OpenAPIHandler constructor security_schemes parameter

```python
    docs = OpenAPIHandler(
        info=Info(
            title="Example API",
            version="0.0.1",
        ),
        security_schemes={
            "oauth2": OAuth2Security(
                flows=OAuthFlows(
                    implicit=OAuthFlow(
                        authorization_url="https://example.com/oauth2/authorize",
                        token_url="https://example.com/oauth2/token",
                        refresh_url="https://example.com/oauth2/refresh",
                        scopes={
                            "read:cats": "Read your cats",
                            "write:cats": "Write your cats",
                        },
                    )
                ),
                description="OAuth2 Auth",
            ),
        },
    )
```

OpenAPI documentation - https://swagger.io/docs/specification/authentication/

### CODE REVIEW

**Comment by tyzhnenko** [comment]
@RobertoPrevato I've faced that BlackSheep can't produce OpenAPI documentation with a security description. As a result Swagger UI can't make requests for endpoints that require auth.

The PR contains improvements for the OpenAPI documentation generator to handle this problem.

**Comment by RobertoPrevato** [comment]
Hi @tyzhnenko 
Thank You for helping with this. This is something I should have documented better, having time. I didn´t document it more just because time is limited and I need to prioritize.

This is mentioned too briefly in the documentation, here https://www.neoteroi.dev/blacksheep/openapi/#altering-the-specification-upon-creation but it is possible to edit the OpenAPI Specification upon creation, to do pretty much anything with it.

For example, to configure security:

```python
from blacksheep import Application
from blacksheep.server.openapi.v3 import OpenAPIHandler
from openapidocs.v3 import Info, OpenAPI, Security, SecurityRequirement

app = Application()


class MyOpenAPIHandler(OpenAPIHandler):
    def on_docs_generated(self, docs: OpenAPI) -> None:
        docs.security = Security([SecurityRequirement("basic", [])])


docs = MyOpenAPIHandler(info=Info(title="Example API", version="0.0.1"))
docs.bind_app(app)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, port=44555)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, port=44555)
```

OpenAPI Specification is vast and there are so many options that not everything should be covered within the `OpenAPIHandler` constructor. The main responsibility of this class is to help with whatever can be generated automatically using the information that is available to the web framework. Then the classes in `essentials-openapi` can be used to describe a specification and generate YAML / JSON.

I try to review your PR tomorrow - I didn´t have time today.

**Comment by tyzhnenko** [comment]
Hi, @RobertoPrevato

I see your points. 

I wanted to make this automatically just using _auth_ attribute of handlers but I didn't find a way unfortunately. Due OpenAPI schema needs a name and scopes for an operator security field we can't use just _handler.auth_ to fill everything automatically.

It makes sense when some endpoints require auth and some can be called anonymously.

**Comment by RobertoPrevato** [comment]
> I wanted to make this automatically just using _auth_ attribute of handlers but I didn't find a way unfortunately. Due OpenAPI schema needs a name and scopes for an operator security field we can't use just _handler.auth_ to fill everything automatically.

Absolutely, I wanted to do the same, but it's a complex topic and it would require a big amount of time to generate auth specs automatically. Not even web frameworks baked by big team working for big corporations offer this feature. Scopes are not always needed because they are only for oauth2 security, but it's anyway challenging to cover all scenarios (basic and API Key would be relatively easy). Another challenge when you use OAuth2, is that the Swagger UI has a dedicated client app registration which is not the same as the app registration used by the web API being documented. There is also the need to keep the web framework itself abstracted away and agnostic of a specific _way of documenting_ APIs, consider:

- OpenAPI Specification v2
- OpenAPI Specification v3
- [AsyncAPI Speficiation v2](https://www.asyncapi.com/docs/reference/specification/v2.0.0)

Both OpenAPI and AsyncAPI are part of the Linux Foundation so they are also both equally legitimate citizens.

> 
> It makes sense when some endpoints require auth and some can be called anonymously.

True.

**Comment by techntools** [comment]
I am gunning for api first approach. Please check this [discussion](https://github.com/Neoteroi/BlackSheep/discussions/344).

**Comment by RobertoPrevato** [comment]
> I am gunning for api first approach. Please check this [discussion](https://github.com/Neoteroi/BlackSheep/discussions/344).

I already apply API First approach to my web apps and dedicated a good deal of time supporting automatic generation of OpenAPI Documentation in blacksheep. Time is limited and it's not possible to cover all possible scenarios, though. In the last days for example I started working on a blacksheep-cli and project templates to support bootstrapping new projects faster + configuration strategy.

**Comment by techntools** [comment]
You are right that time is limited.

I think spec first instead of api first is the right choice of words for what i was trying to say.

But can not cover all scenarios and framework does offer nice ways to cover scenarios not built into it.

**Comment by techntools** [comment]
Would the cli support management command like django does ? I find them useful.

**Pull request merged**
