### PR TITLE
WebSocket support follow-up

### PR DESCRIPTION
**Pull request by Klavionik**
This PR is a follow-up to #222, adding some improvements to it.

### CODE REVIEW

**Comment by Klavionik** [comment]
@RobertoPrevato I could try to write some simple tests for the websocket module and update the docs, if you'd like.

**Comment by Klavionik** [comment]
@RobertoPrevato I made an attempt to replace state assertions with exceptions. Though I'm not sure, I'm happy about it. On one hand, we now have much more helpful error messages and that's good! On the other hand, the methods look a bit more complicated now, though I've tried to be concise while providing as much information as possible.

I guess the assert statement was the right choice in the first place because it represents a kind of error that's not meant to be handled, an error you can't recover from. These state checks are exactly this kind of error. Maybe we should leave the asserts, but provide a friendly error message?

**Comment by RobertoPrevato** [comment]
@Klavionik sorry for replying late, I was busier than usual in the last days. Replying in order:
* sure, I welcome your contributions, and I like very much the way you added support for web sockets to the framework (this was one of the topics at the top of my TODO lists - but in the last weeks I dedicated some time to prepare tutorials instead, about the [Torino demo project](https://github.com/Neoteroi/Torino)). About the documentation, it is currently in Azure DevOps, I will try to move it to GitHub (this is another thing I planned to do a long time ago) - maybe it's best if I first move it here in GitHub, then you can take a look at it?
* I think asserts are not the right choice to raise exceptions in situations about the state of a object. I recall that Yury Selivanov was recommending the same when I worked for EdgeDB and was adding type check coverage (i.e. assertions can be used to make mypy happy about type checks, but don't always make sense)

**Comment by RobertoPrevato** [comment]
@Klavionik (second message for today) - this morning I dedicated some time to transfer the documentation from Azure DevOps to this GitHub repository: https://github.com/Neoteroi/BlackSheep-Docs

If you have time and desire to contribute, you can submit a PR to this repository. 😊
PS. I like your changes in this PR, I think we can merge it. Later today I'll try to ask your recommendation about this topic.

**Comment by RobertoPrevato** [comment]
I created a PR to your branch https://github.com/Klavionik/BlackSheep/pull/1

**Comment by Klavionik** [comment]
Hi, thanks for the kind words! It's great that docs are available on GitHub now, I will send a PR soon.

I also reviewed your PR, and I approve it. A couple of comments:

1. You must be right about the `send` method. There is probably no point in having a public method that could send arbitrary data straight to the protocol server just to crash it. :) Contrary to receiving a raw message with `receive`, I can't think of any application for `send` (at least right now).

2.  I actually wanted to annotate the `mode` parameter with the MessageMode enum at first, but I was afraid that I'm not in the right to restrict the user to use only enum values. Though, if that's the approach that the framework promotes, then I'm totally fine with it.

If you're done, I could merge your PR into mine.

**Comment by Klavionik** [comment]
I noticed that you can't have a WebSocket route and a GET route sharing the same pattern. Not much of a surprise, the `ws` method right now is just an alias for creating a GET route. 

Maybe we should allow users to create WS and GET routes with the same pattern? I'm thinking of marking WS routes somehow and using this mark when checking for duplicates/matching a route.

**Comment by Klavionik** [comment]
@RobertoPrevato Please note that I've added new commits to the branch. It's the `add_ws` method for the router and a test for it.

**Comment by RobertoPrevato** [comment]
> I noticed that you can't have a WebSocket route and a GET route sharing the same pattern. Not much of a surprise, the `ws` method right now is just an alias for creating a GET route.
> 
> Maybe we should allow users to create WS and GET routes with the same pattern? I'm thinking of marking WS routes somehow and using this mark when checking for duplicates/matching a route.

Good point. Even though I cannot really think of a useful use case for wanting the same route to register one handler for web sockets and one for regular HTTP requests, we could achieve this adding a dedicated member to the `HTTPMethod` class.

Something like:

```python
class HTTPMethod:
    GET = "GET"
    GET_WS = "GET_WS"
    ...
```

Even though this might seem ridiculous, I added this class really just to not write the same strings everywhere - not to provide a list of standard HTTP methods. We might handle it this way.

**Comment by Klavionik** [comment]
@RobertoPrevato I've merged your contributions into this branch. Thanks!

> we could achieve this adding a dedicated member to the HTTPMethod class

Yep, that's a possible solution. Would you mind implementing it? I guess you can then rename `HTTPMethod` into `RouteMethod` or something like that.

I added one more commit, importing WebSocket and WebSocketDisconnectError into `blacksheep` package so that the user could import it straight from the package, just like `Application` or `Request`.

I'm also working on the documentation. I guess I'll send the PR tomorrow. Do you mind if I bump the `mkdocs-material` package to version `7.3.1`? I'd like to use tabbed code blocks, it's a neat feature. :) It doesn't seem to break anything.

**Comment by RobertoPrevato** [comment]
Thank You! Sure, I will implement the `HTTPMethod` change (I'll merge this one and add it in another PR, though). And sure, feel free to update `mkdocs-material`, too. :)

**Pull request merged**
