### PR TITLE
add Python 3.12 support

### PR DESCRIPTION
**Pull request by bymoye**

### CODE REVIEW

**Comment by RobertoPrevato** [comment]
Thank You @bymoye for your contribution!
I see there is a problem with the change for `import pkg_resources`, I try to investigate the issue.

**Comment by bymoye** [comment]
> 谢谢@bymoye为了您的贡献！ 我发现 的更改存在问题`import pkg_resources`，我尝试调查该问题。

sorry，I forgot to do compatibility testing, I'll see how to handle this

**Comment by bymoye** [comment]
Maybe we can use with pathlib.Path.open() instead of with open("path") @RobertoPrevato

**Comment by RobertoPrevato** [comment]
> Maybe we can use with pathlib.Path.open() instead of with open("path") @RobertoPrevato

No, thank you, I like the `open` code API just fine. Your pull request is already rich of useful changes anyway! I applied corrections to make things work in all supported Python versions - there was something wrong in the new code to replace `pkg_resources` and a coincidental issue with tests running with Pydantic v2.

**Pull request merged**
